"""Shell-completion scripts generated by the Lunch Money MCP CLI."""

from __future__ import annotations

from typing import Literal

CompletionShell = Literal["bash", "zsh"]
"""Shells with built-in completion script support."""

_COMMAND_OPTIONS: dict[str, tuple[str, ...]] = {
    "mcp": (
        "--stdio",
        "--sse",
        "--http",
        "--streamable-http",
        "--stateless",
        "--no-stateless",
        "--ephemeral",
        "--no-ephemeral",
        "--host",
        "--port",
        "--trusted-proxy-ips",
        "--allowed-hosts",
        "--cors-allowed-origins",
        "--max-request-body-bytes",
        "--request-timeout-seconds",
        "--max-concurrent-requests",
        "--rate-limit-requests",
        "--rate-limit-window-seconds",
        "--mcp-oauth-config-url",
        "--mcp-oauth-client-id",
        "--mcp-oauth-base-url",
        "--mcp-oauth-audience",
        "--help",
    ),
    "serve": (
        "--environment",
        "--stateless",
        "--no-stateless",
        "--ephemeral",
        "--no-ephemeral",
        "--sync-safety-margin-minutes",
        "--schedule-cron",
        "--schedule-timezone",
        "--schedule-days",
        "--embed-scheduler",
        "--no-embed-scheduler",
        "--host",
        "--port",
        "--trusted-proxy-ips",
        "--allowed-hosts",
        "--cors-allowed-origins",
        "--max-request-body-bytes",
        "--request-timeout-seconds",
        "--max-concurrent-requests",
        "--rate-limit-requests",
        "--rate-limit-window-seconds",
        "--mcp-oauth-config-url",
        "--mcp-oauth-client-id",
        "--mcp-oauth-base-url",
        "--mcp-oauth-audience",
        "--help",
    ),
    "schedule": (
        "--stateless",
        "--no-stateless",
        "--ephemeral",
        "--no-ephemeral",
        "--sync-safety-margin-minutes",
        "--schedule-cron",
        "--schedule-timezone",
        "--schedule-days",
        "--help",
    ),
    "sync": (
        "--days",
        "--incremental",
        "--stateless",
        "--no-stateless",
        "--sync-safety-margin-minutes",
        "--help",
    ),
    "doctor": ("--help",),
    "version": ("--help",),
}
"""Non-secret command options offered by generated completion scripts."""


def render_completion(shell: CompletionShell) -> str:
    """Generate an installable completion script for one supported shell.

    Parameters
    ----------
    shell : CompletionShell
        Target shell syntax to render.

    Returns
    -------
    str
        Completion script for source or installation by the operator.
    """
    if shell == "bash":
        return _render_bash_completion()
    return _render_zsh_completion()


def _render_bash_completion() -> str:
    """Render completion for Bash's programmable completion interface."""
    command_options = "\n".join(
        f'        {command}) options="{" ".join(options)}" ;;'
        for command, options in _COMMAND_OPTIONS.items()
    )
    return f"""# Bash completion for lunchmoney-mcp.
_lunchmoney_mcp() {{
    local current command options
    current="${{COMP_WORDS[COMP_CWORD]}}"
    command="${{COMP_WORDS[1]}}"

    if [[ "$COMP_CWORD" -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "mcp serve schedule sync doctor version --help --print-completion" -- "$current") )
        return 0
    fi

    if [[ "$command" == "--print-completion" ]]; then
        COMPREPLY=( $(compgen -W "bash zsh" -- "$current") )
        return 0
    fi

    case "$command" in
{command_options}
    esac
    COMPREPLY=( $(compgen -W "$options" -- "$current") )
}}

complete -F _lunchmoney_mcp lunchmoney-mcp
"""


def _render_zsh_completion() -> str:
    """Render completion for Zsh's native completion system."""
    command_cases = "\n".join(
        f"        {command}) options=({' '.join(options)}) ;;"
        for command, options in _COMMAND_OPTIONS.items()
    )
    return f"""#compdef lunchmoney-mcp

_lunchmoney_mcp() {{
    local -a commands options
    commands=(
        'mcp:Run the standalone MCP server'
        'serve:Run local FastAPI'
        'schedule:Run the opt-in scheduler'
        'sync:Run one foreground synchronization'
        'doctor:Check local configuration'
        'version:Print the installed package version'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' commands
        return
    fi

    if [[ "${{words[2]}}" == "--print-completion" ]]; then
        _describe 'shell' '(bash zsh)'
        return
    fi

    case "${{words[2]}}" in
{command_cases}
    esac
    _describe 'option' options
}}

compdef _lunchmoney_mcp lunchmoney-mcp
"""


__all__ = ["CompletionShell", "render_completion"]
