# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.2.1
_src_path: https://github.com/juftin/cookiecutter-python.git
build_docker_image: true
default_branch: main
default_python_version: '3.13'
development_status: 'Development Status :: 3 - Alpha'
favicon: https://juftin.com/favicon.ico
github_user: juftin
license: MIT
logo_url: https://raw.githubusercontent.com/juftin/juftin/main/static/juftin.png
package_name: lunchmoney-mcp
project_description: Lunch Money Application
project_name: lunchmoney-mcp
publish_to_docker_hub: false
publish_to_pypi: false
user_email: juftin@juftin.com
user_name: Justin Flannery
version: 0.1.0
